apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ci84nyf4h-go
  janus-idp.io/tekton: ci84nyf4h-go
  backstage.io/kubernetes-id: ci84nyf4h-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ci84nyf4h-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
